CREATE TABLE "catalog_items" (
	"id" text PRIMARY KEY NOT NULL,
	"title" text NOT NULL,
	"author" text NOT NULL,
	"price" double precision NOT NULL,
	"type" text NOT NULL,
	"format" text NOT NULL,
	"description" text NOT NULL,
	"cover_url" text,
	"media_name" text,
	"media_url" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"status" text DEFAULT 'live',
	"rating" double precision,
	"review_count" integer,
	"allow_librarian" boolean DEFAULT true,
	"allow_challenge" boolean DEFAULT true,
	"quiz_mood" text[],
	"quiz_format" text[],
	"quiz_hook" text[],
	"quiz_pace" text[],
	"promo_flat_bonus" double precision,
	"promo_override" jsonb
);
