import { useState, useEffect, useCallback } from "react";
import { hasRecoveryKey, generateRecoveryKey, verifyRecoveryKey } from "~/data/adminRecovery";
import { AdminCredentialsForm } from "~/components/AdminCredentialsForm";

interface AdminForcedSetupProps {
  /** Called once real credentials have been saved — hasAdminCredentials()
   *  will return true from now on, and the normal AdminLogin passcode flow
   *  takes over. */
  onComplete: () => void;
}

/**
 * Blocks the admin dashboard until real credentials replace the hardcoded
 * fallback passcode. Shown whenever hasAdminCredentials() reports false
 * (no passcodeHash set yet in the admin_auth table).
 *
 * setAdminCredentials() requires proof of authorization — either an
 * existing admin session (not available here, nothing has been set up yet)
 * or the recovery phrase. So this screen bootstraps one: on a truly fresh
 * deployment no recovery phrase exists either, and generateRecoveryKey()
 * is unrestricted in that case (see src/data/adminRecovery.ts). If a
 * recovery phrase was already generated by an earlier, interrupted setup
 * attempt, the admin is asked to paste it in instead.
 */
export function AdminForcedSetup({ onComplete }: AdminForcedSetupProps) {
  const [phase, setPhase] = useState<"loading" | "manualPhrase" | "ready">("loading");
  const [recoveryPhrase, setRecoveryPhrase] = useState("");
  const [freshlyGenerated, setFreshlyGenerated] = useState(false);
  const [phraseInput, setPhraseInput] = useState("");
  const [phraseError, setPhraseError] = useState("");

  useEffect(() => {
    let cancelled = false;
    (async () => {
      const exists = await hasRecoveryKey();
      if (cancelled) return;
      if (!exists) {
        const key = await generateRecoveryKey();
        if (cancelled) return;
        setRecoveryPhrase(key);
        setFreshlyGenerated(true);
        setPhase("ready");
      } else {
        setPhase("manualPhrase");
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  const handleVerifyPhrase = useCallback(async () => {
    const valid = await verifyRecoveryKey(phraseInput.trim());
    if (valid) {
      setRecoveryPhrase(phraseInput.trim());
      setPhraseError("");
      setPhase("ready");
    } else {
      setPhraseError("Invalid recovery key. Please check your 12-word phrase.");
    }
  }, [phraseInput]);

  return (
    <div className="flex min-h-[70vh] items-center justify-center px-4">
      <div className="w-full max-w-md">
        <div
          className="rounded-2xl border p-8 shadow-xl backdrop-blur-sm"
          style={{
            borderColor: "var(--color-border)",
            backgroundColor: "color-mix(in srgb, var(--color-surface) 50%, transparent)",
          }}
        >
          <div
            className="mx-auto mb-6 flex h-14 w-14 items-center justify-center rounded-full"
            style={{ backgroundColor: "color-mix(in srgb, var(--color-primary) 20%, transparent)" }}
          >
            <svg
              className="h-7 w-7"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth={1.5}
              stroke="currentColor"
              aria-hidden="true"
              style={{ color: "var(--color-primary)" }}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M9 12.75L11.25 15 15 9.75m-3-7.036A11.959 11.959 0 013.598 6 11.99 11.99 0 003 9.749c0 5.592 3.824 10.29 9 11.623 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.571-.598-3.751h-.152c-3.196 0-6.1-1.248-8.25-3.285z"
              />
            </svg>
          </div>

          <h1 className="text-center text-2xl font-bold" style={{ color: "var(--color-text)" }}>
            Secure This Admin Panel
          </h1>
          <p className="mt-2 text-center text-sm" style={{ color: "var(--color-text-muted)" }}>
            This deployment is still using the default admin passcode. Set your own email and passcode
            before continuing.
          </p>

          {phase === "loading" && (
            <p className="mt-8 text-center text-sm" style={{ color: "var(--color-text-muted)" }}>
              Preparing setup…
            </p>
          )}

          {phase === "manualPhrase" && (
            <div className="mt-8 space-y-4">
              <p className="text-xs text-center" style={{ color: "var(--color-text-muted)" }}>
                A recovery key already exists for this deployment. Enter it below to continue setup.
              </p>
              <textarea
                value={phraseInput}
                onChange={(e) => { setPhraseInput(e.target.value); setPhraseError(""); }}
                className="w-full rounded-lg border px-4 py-3 text-sm transition-colors focus:outline-none focus:ring-1"
                style={{
                  backgroundColor: "var(--color-surface)",
                  color: "var(--color-text)",
                  borderColor: phraseError ? "#ef4444" : "var(--color-border)",
                }}
                rows={3}
                placeholder="Enter your 12-word recovery phrase..."
              />
              {phraseError && (
                <p className="text-sm text-red-400" role="alert">{phraseError}</p>
              )}
              <button
                type="button"
                onClick={handleVerifyPhrase}
                className="w-full rounded-lg px-4 py-3 text-sm font-semibold text-white shadow-sm transition-all hover:brightness-110"
                style={{ backgroundColor: "var(--color-primary)" }}
              >
                Verify & Continue
              </button>
            </div>
          )}

          {phase === "ready" && (
            <div className="mt-8 space-y-4">
              {freshlyGenerated && (
                <div className="rounded-lg border p-3" style={{ borderColor: "var(--color-border)", backgroundColor: "var(--color-surface)" }}>
                  <p className="text-xs font-bold mb-1" style={{ color: "var(--color-text)" }}>
                    Your Master Recovery Key:
                  </p>
                  <p className="text-xs font-mono leading-relaxed break-all" style={{ color: "var(--color-primary)" }}>
                    {recoveryPhrase}
                  </p>
                  <p className="text-[10px] mt-1" style={{ color: "var(--color-text-muted)" }}>
                    Save this in a safe place. It cannot be recovered.
                  </p>
                </div>
              )}
              <AdminCredentialsForm
                recoveryPhrase={recoveryPhrase}
                onSuccess={onComplete}
                submitLabel="Create Admin Account"
              />
            </div>
          )}

          <div
            className="mt-6 flex items-center justify-between rounded-lg border px-4 py-3 opacity-60"
            style={{ borderColor: "var(--color-border)" }}
          >
            <span className="text-xs font-medium" style={{ color: "var(--color-text-muted)" }}>
              Enable login with Google (coming soon)
            </span>
            <button
              type="button"
              disabled
              aria-disabled="true"
              aria-label="Enable login with Google — coming soon, not yet available"
              title="Coming soon"
              className="relative h-5 w-9 shrink-0 rounded-full cursor-not-allowed"
              style={{ backgroundColor: "var(--color-border)" }}
            >
              <span className="absolute left-0.5 top-0.5 h-4 w-4 rounded-full bg-white" />
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
